[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xf/home/tntuser55)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x11\0\0\x6G\0\0\x4&\0\0\t\xe0\0\0\0\x15\0\0\x6K\0\0\x4\"\0\0\t\xdc\0\0\0\x2\0\0\0\0\x4\x38\0\0\0\x15\0\0\x6K\0\0\x4\"\0\0\t\xdc)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list="https://r1---sn-jvh2vgp0h-jaul.googlevideo.com/videoplayback?expire=1578713034&ei=aesYXt2HO8Sgj-8PwpGhaA&ip=67.197.126.17&id=o-AGed0JMEcfSjCs2o0TQflFzTcfM8CYiKJAvaGeJYFgkN&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-jvh2vgp0h-jaul%2Csn-5uaezny6&ms=au%2Crdu&mv=m&mvi=0&pl=18&initcwndbps=1901250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=12671397&dur=778.741&lmt=1542337206852014&mt=1578691317&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAPXxAUPj2yCWFdpwJ566ztFjk6aiWELotuNdCMsxRX2UAiEAmm8areB4WMFWjv0eJX2kLY8bVf4UESIKvbLVigaIhHQ%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgQ42_tTG0UKdUyYtn_qBTNGcXNagt-FmI_Ex7nv0kutwCIG6n51pH4iTujkkQKdwTjQz6TXmN3IC_HQt3w6LSi85w&ratebypass=yes", "https://r2---sn-jvh2vgp0h-jaue.googlevideo.com/videoplayback?expire=1578712417&ei=AekYXuepNYGCkAS3rIWYDw&ip=67.197.126.17&id=o-AJMpmnA7b-ed_ZWYxEQZ-l-PXYfw4q0dST_LWmBO7-Ut&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-jvh2vgp0h-jaue%2Csn-5uaeznkz&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=1913750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5848944&dur=366.861&lmt=1578625931688712&mt=1578690715&fvip=5&keepalive=yes&fexp=23842630&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgcaT763nHGt-PF5_HgW4QMlpALsK6urYcoSyy69_7_VoCIEQzjKUcfcHZkXluvWjyNv8j6DG2DCvi_116cIESPzct&sig=ALgxI2wwRgIhAIEf6Njehjqx8DFdSykc1QSrGVxgRfGncaDjH7IHWTVTAiEAp_6ZAoHygDY3UZYHGMbAxy87ZhXjtLyRE6ScC1pkNTU=&ratebypass=yes"
times=193674, 90794
